version: "3.3"
services:
  backend:
    container_name: backend
    build: .
    command: gunicorn core.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 80:8000
    depends_on:
      - db
    networks:
      - backend-network

  db:
    container_name: psql-db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - backend-network
volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge